title: Introduction à la programmation avec Python (In2Py)
description: ""


navigation:
  Home: "/"
  Synopsis: "/synopsis"
  Organisation: "/organisation"
  Ressources: "/ressources"
  Opportunities: "/opportunities"
  Instructor: "/instructeur"
  
  


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
