title: Experimental Mathematics with SAGEMath (EMS)
description: ""


navigation:
  Home: "/"
  Synopsis: "/synopsis"
  Organisation: "/organisation"
  Interact Competition: "/interact"
  Ressources: "/resources"
  Opportunities: "/opportunities"
  Instructor: "/instructeur"
  

  
  


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
