title:        Workshop on Computational Topology & Quantum Computing  
description:  WoComToQC 


navigation:
  Home: "/"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Organisers: "/organisers"
  Programme Committee: "/committee"
  FAQ: "/faq"
 
  


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
