title:        Workshop on Computational Topology & Quantum Computing  
description:  WoComToQC - Topological Data Analysis & Quantum Computing for beginners


navigation:
  Home: "/"
  Background: "/background"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Organisers: "/organisers"
  Render unto Ceasar: "/render"
  FAQ: "/faq"
 
  


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
